import type { Deal } from "@/lib/types/database";

function futureDate(days: number): string {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}

function pastDate(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const DEMO_DEALS: Deal[] = [
  {
    id: "demo-1",
    title: "Netflix Premium 50% Off",
    description: "Get Netflix Premium plan at half price! Stream in 4K HDR on up to 4 devices. Limited time offer for new and returning subscribers.",
    provider: "Netflix",
    category: "Streaming",
    country: "GLOBAL",
    start_at: pastDate(2),
    end_at: futureDate(3),
    original_price: 22.99,
    deal_price: 11.49,
    currency: "USD",
    discount_percent: 50,
    image_url: "https://images.unsplash.com/photo-1574375927938-d5a98e8d7e28?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://netflix.com",
    created_by: "demo",
    status: "approved",
    heat_score: 85,
    view_count: 340,
    created_at: pastDate(5),
    updated_at: pastDate(1),
  },
  {
    id: "demo-2",
    title: "Steam Summer Sale — Up to 80% Off",
    description: "The legendary Steam Summer Sale is here! Thousands of games discounted up to 80%. Daily rotating flash deals available.",
    provider: "Steam",
    category: "Gaming",
    country: "GLOBAL",
    start_at: pastDate(1),
    end_at: futureDate(7),
    original_price: null,
    deal_price: null,
    currency: "USD",
    discount_percent: 80,
    image_url: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://store.steampowered.com",
    created_by: "demo",
    status: "approved",
    heat_score: 120,
    view_count: 580,
    created_at: pastDate(3),
    updated_at: pastDate(0),
  },
  {
    id: "demo-3",
    title: "PS Plus Annual -30%",
    description: "PlayStation Plus yearly subscription at 30% off. Access hundreds of PS4 and PS5 games, online multiplayer.",
    provider: "PlayStation",
    category: "Gaming",
    country: "US",
    start_at: pastDate(1),
    end_at: futureDate(5),
    original_price: 79.99,
    deal_price: 55.99,
    currency: "USD",
    discount_percent: 30,
    image_url: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://playstation.com",
    created_by: "demo",
    status: "approved",
    heat_score: 67,
    view_count: 215,
    created_at: pastDate(4),
    updated_at: pastDate(1),
  },
  {
    id: "demo-4",
    title: "Amazon Prime -40% (Turkey)",
    description: "Amazon Prime subscription at 40% discount for Turkey. Free shipping, Prime Video, Prime Gaming.",
    provider: "Amazon",
    category: "Streaming",
    country: "TR",
    start_at: pastDate(1),
    end_at: futureDate(2),
    original_price: 57.99,
    deal_price: 34.79,
    currency: "TRY",
    discount_percent: 40,
    image_url: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://amazon.com.tr",
    created_by: "demo",
    status: "approved",
    heat_score: 45,
    view_count: 178,
    created_at: pastDate(2),
    updated_at: pastDate(0),
  },
  {
    id: "demo-5",
    title: "X Premium -50%",
    description: "X (formerly Twitter) Premium at half price! Get verified badge, edit posts, and ad-free timeline.",
    provider: "X (Twitter)",
    category: "Social",
    country: "GLOBAL",
    start_at: pastDate(3),
    end_at: futureDate(4),
    original_price: 8.0,
    deal_price: 4.0,
    currency: "USD",
    discount_percent: 50,
    image_url: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://x.com",
    created_by: "demo",
    status: "approved",
    heat_score: 38,
    view_count: 145,
    created_at: pastDate(6),
    updated_at: pastDate(2),
  },
  {
    id: "demo-6",
    title: "Spotify Family -25% (Germany)",
    description: "Spotify Family plan for up to 6 accounts at 25% off. Premium features for everyone.",
    provider: "Spotify",
    category: "Music",
    country: "DE",
    start_at: pastDate(1),
    end_at: futureDate(10),
    original_price: 16.99,
    deal_price: 12.74,
    currency: "EUR",
    discount_percent: 25,
    image_url: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://spotify.com",
    created_by: "demo",
    status: "approved",
    heat_score: 55,
    view_count: 230,
    created_at: pastDate(7),
    updated_at: pastDate(3),
  },
  {
    id: "demo-7",
    title: "Adobe Creative Cloud -40%",
    description: "Full Adobe Creative Cloud suite at 40% off. Photoshop, Illustrator, Premiere Pro, After Effects.",
    provider: "Adobe",
    category: "Software",
    country: "US",
    start_at: pastDate(2),
    end_at: futureDate(6),
    original_price: 59.99,
    deal_price: 35.99,
    currency: "USD",
    discount_percent: 40,
    image_url: "https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://adobe.com",
    created_by: "demo",
    status: "approved",
    heat_score: 72,
    view_count: 310,
    created_at: pastDate(5),
    updated_at: pastDate(1),
  },
  {
    id: "demo-8",
    title: "NordVPN -70% + 3 Months Free",
    description: "NordVPN 2-year plan at 70% off plus 3 extra months free. Military-grade encryption, 5500+ servers.",
    provider: "NordVPN",
    category: "Security",
    country: "GLOBAL",
    start_at: pastDate(3),
    end_at: futureDate(14),
    original_price: 11.99,
    deal_price: 3.59,
    currency: "USD",
    discount_percent: 70,
    image_url: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://nordvpn.com",
    created_by: "demo",
    status: "approved",
    heat_score: 95,
    view_count: 420,
    created_at: pastDate(8),
    updated_at: pastDate(2),
  },
  {
    id: "demo-9",
    title: "Microsoft 365 Family -35%",
    description: "Microsoft 365 Family for up to 6 people. Word, Excel, PowerPoint, OneDrive 1TB per person.",
    provider: "Microsoft",
    category: "Software",
    country: "GLOBAL",
    start_at: pastDate(4),
    end_at: futureDate(1),
    original_price: 99.99,
    deal_price: 64.99,
    currency: "USD",
    discount_percent: 35,
    image_url: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://microsoft.com",
    created_by: "demo",
    status: "approved",
    heat_score: 110,
    view_count: 490,
    created_at: pastDate(10),
    updated_at: pastDate(1),
  },
  {
    id: "demo-10",
    title: "Apple Music Student -50%",
    description: "Apple Music student plan at 50% off. Over 100 million songs, spatial audio, lossless quality.",
    provider: "Apple",
    category: "Music",
    country: "GLOBAL",
    start_at: pastDate(1),
    end_at: futureDate(30),
    original_price: 10.99,
    deal_price: 5.49,
    currency: "USD",
    discount_percent: 50,
    image_url: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=340&fit=crop",
    storage_path: null,
    external_url: "https://apple.com/music",
    created_by: "demo",
    status: "approved",
    heat_score: 30,
    view_count: 95,
    created_at: pastDate(2),
    updated_at: pastDate(0),
  },
];

export function getDemoEndingSoon(): Deal[] {
  return [...DEMO_DEALS]
    .filter((d) => new Date(d.end_at) > new Date())
    .sort((a, b) => new Date(a.end_at).getTime() - new Date(b.end_at).getTime());
}

export function getDemoPopular(): Deal[] {
  return [...DEMO_DEALS].sort((a, b) => b.heat_score - a.heat_score);
}

export function getDemoNewest(): Deal[] {
  return [...DEMO_DEALS].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );
}
